from enum import StrEnum


class UserRole(StrEnum):
    STANDARD_USER = "STANDARD_USER"
    ADMIN = "ADMIN"


class ApplicationStatus(StrEnum):
    DRAFT = "DRAFT"
    APPLIED = "APPLIED"
    SCREENING = "SCREENING"
    INTERVIEW = "INTERVIEW"
    OFFER = "OFFER"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
    ARCHIVED = "ARCHIVED"


class WorkMode(StrEnum):
    REMOTE = "REMOTE"
    HYBRID = "HYBRID"
    ONSITE = "ONSITE"


class ApplicationSource(StrEnum):
    LINKEDIN = "LINKEDIN"
    INDEED = "INDEED"
    COMPANY_WEBSITE = "COMPANY_WEBSITE"
    RECRUITER = "RECRUITER"
    REFERRAL = "REFERRAL"
    HANDSHAKE = "HANDSHAKE"
    CAREER_FAIR = "CAREER_FAIR"
    OTHER = "OTHER"


class ApplicationSort(StrEnum):
    UPDATED_DESC = "updated_desc"
    UPDATED_ASC = "updated_asc"


class ActivityType(StrEnum):
    APPLICATION_CREATED = "APPLICATION_CREATED"
    STATUS_CHANGED = "STATUS_CHANGED"
    FOLLOW_UP_COMPLETED = "FOLLOW_UP_COMPLETED"
    FOLLOW_UP_RESCHEDULED = "FOLLOW_UP_RESCHEDULED"
    NOTE_CREATED = "NOTE_CREATED"
    NOTE_UPDATED = "NOTE_UPDATED"
    NOTE_DELETED = "NOTE_DELETED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    INTERVIEW_UPDATED = "INTERVIEW_UPDATED"
    INTERVIEW_STATUS_CHANGED = "INTERVIEW_STATUS_CHANGED"


class DemoWorkspaceState(StrEnum):
    PROVISIONING = "PROVISIONING"
    READY = "READY"
    FAILED = "FAILED"
