from enum import StrEnum


class UserRole(StrEnum):
    STANDARD_USER = "STANDARD_USER"
    ADMIN = "ADMIN"


class ApplicationStatus(StrEnum):
    DRAFT = "DRAFT"
    APPLIED = "APPLIED"
    SCREENING = "SCREENING"
    INTERVIEW = "INTERVIEW"
    OFFER = "OFFER"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
    ARCHIVED = "ARCHIVED"


class WorkMode(StrEnum):
    REMOTE = "REMOTE"
    HYBRID = "HYBRID"
    ONSITE = "ONSITE"


class ApplicationSource(StrEnum):
    LINKEDIN = "LINKEDIN"
    INDEED = "INDEED"
    COMPANY_WEBSITE = "COMPANY_WEBSITE"
    RECRUITER = "RECRUITER"
    REFERRAL = "REFERRAL"
    HANDSHAKE = "HANDSHAKE"
    CAREER_FAIR = "CAREER_FAIR"
    OTHER = "OTHER"


class RoleFamily(StrEnum):
    GENERAL = "GENERAL"
    SOFTWARE_IT = "SOFTWARE_IT"
    CUSTOMER_SERVICE = "CUSTOMER_SERVICE"
    SALES = "SALES"
    MARKETING_COMMUNICATIONS = "MARKETING_COMMUNICATIONS"
    FINANCE_ACCOUNTING = "FINANCE_ACCOUNTING"
    HUMAN_RESOURCES = "HUMAN_RESOURCES"
    ADMINISTRATIVE = "ADMINISTRATIVE"
    PROJECT_PROGRAM_MANAGEMENT = "PROJECT_PROGRAM_MANAGEMENT"
    OPERATIONS_LOGISTICS = "OPERATIONS_LOGISTICS"
    MANUFACTURING_SKILLED_TRADES = "MANUFACTURING_SKILLED_TRADES"
    HOSPITALITY_FOOD_SERVICE = "HOSPITALITY_FOOD_SERVICE"
    HEALTHCARE = "HEALTHCARE"
    EDUCATION = "EDUCATION"
    MANAGEMENT_LEADERSHIP = "MANAGEMENT_LEADERSHIP"
    EXECUTIVE = "EXECUTIVE"


class ApplicationSort(StrEnum):
    UPDATED_DESC = "updated_desc"
    UPDATED_ASC = "updated_asc"


class StageAgeBucket(StrEnum):
    ZERO_TO_SEVEN = "0-7"
    EIGHT_TO_FOURTEEN = "8-14"
    FIFTEEN_TO_THIRTY = "15-30"
    THIRTY_ONE_PLUS = "31+"


class FollowUpFilter(StrEnum):
    NEEDS_ATTENTION = "NEEDS_ATTENTION"


class NextStepResponsibility(StrEnum):
    CANDIDATE = "CANDIDATE"
    EMPLOYER = "EMPLOYER"
    NONE = "NONE"


class ActivityType(StrEnum):
    APPLICATION_CREATED = "APPLICATION_CREATED"
    STATUS_CHANGED = "STATUS_CHANGED"
    FOLLOW_UP_COMPLETED = "FOLLOW_UP_COMPLETED"
    FOLLOW_UP_RESCHEDULED = "FOLLOW_UP_RESCHEDULED"
    NEXT_STEP_UPDATED = "NEXT_STEP_UPDATED"
    NOTE_CREATED = "NOTE_CREATED"
    NOTE_UPDATED = "NOTE_UPDATED"
    NOTE_DELETED = "NOTE_DELETED"
    INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
    INTERVIEW_UPDATED = "INTERVIEW_UPDATED"
    INTERVIEW_WORKSPACE_UPDATED = "INTERVIEW_WORKSPACE_UPDATED"
    INTERVIEW_STATUS_CHANGED = "INTERVIEW_STATUS_CHANGED"


class DemoWorkspaceState(StrEnum):
    PROVISIONING = "PROVISIONING"
    READY = "READY"
    FAILED = "FAILED"
