// Reviewed CloudFormation inventory, including three conditionally deployed SNS resources.
export const REVIEWED_RESOURCES = Object.freeze({
  WorkspaceTable68AC2584: 'AWS::DynamoDB::Table',
  FrontendHostingApp3EC0FC15: 'AWS::Amplify::App',
  FrontendHostingBranchB5734B41: 'AWS::Amplify::Branch',
  OperationalLogsBackendFunctionLogs44D131F8: 'AWS::Logs::LogGroup',
  OperationalLogsHttpApiAccessLogs3515ABA0: 'AWS::Logs::LogGroup',
  BackendApiCursorSigningSecret5EF895FB: 'AWS::SecretsManager::Secret',
  BackendApiDemoSessionSigningSecretB7E1C367: 'AWS::SecretsManager::Secret',
  BackendApiExecutionRoleF9E94D3B: 'AWS::IAM::Role',
  BackendApiExecutionRoleDefaultPolicyDE57D6A3: 'AWS::IAM::Policy',
  BackendApiBackendFunctionFFB5248D: 'AWS::Lambda::Function',
  BackendApiHttpApiB4B1202A: 'AWS::ApiGatewayV2::Api',
  BackendApiHttpApiDefaultRouteBackendIntegrationC791C627: 'AWS::ApiGatewayV2::Integration',
  BackendApiHttpApiDefaultRouteBackendIntegrationPermission521AD465: 'AWS::Lambda::Permission',
  BackendApiHttpApiDefaultRoute408A2CCF: 'AWS::ApiGatewayV2::Route',
  BackendApiHttpApiDefaultStage89B5186D: 'AWS::ApiGatewayV2::Stage',
  OperationsOperationalAlerts7AC1A668: 'AWS::SNS::Topic',
  OperationsOperationalAlertSubscription953AAEA9: 'AWS::SNS::Subscription',
  OperationsOperationalAlertPolicy4A085B4E: 'AWS::SNS::TopicPolicy',
  OperationsLambdaErrors5904FFE2: 'AWS::CloudWatch::Alarm',
  OperationsLambdaThrottles66F0659C: 'AWS::CloudWatch::Alarm',
  OperationsHttpApiServerErrors8A0F4370: 'AWS::CloudWatch::Alarm',
  OperationsDynamoDBThrottlesAF8DF63F: 'AWS::CloudWatch::Alarm',
  OperationsDynamoDBSystemErrorsB63796D3: 'AWS::CloudWatch::Alarm',
  OperationsOperationalDashboard098A469E: 'AWS::CloudWatch::Dashboard',
  OperationsMonthlyCostBudgetFC194922: 'AWS::Budgets::Budget',
});
export const REVIEWED_RESOURCE_COUNT = 25;
